### ISSUE TITLE
在我电脑eclipse导入之后运行，会报错。

### ISSUE THREAD

**Issue by nijian81** [leancloud/android-todolist#1]
会报类未发现异常

**Comment by lzwjava** [comment]
这里有 Eclipse 的版本，点击右边 Download Zip 可下载下来。

https://github.com/leancloud/android-sdk-demos/tree/51456a01d403697694ee53bb0b82a34164dc8f61

**Comment by lzwjava** [comment]
你好，稍微补充了下说明，https://github.com/leancloud/android-todolist/blob/master/README.md#如何运行
